### ISSUE TITLE
1.17.1 Compatibility

### ISSUE THREAD

**Issue by Altirix** [motz0815/Randomizer#1]
[Rand.zip](https://github.com/motz0815/Randomizer/files/6825524/Rand.zip)

the mod is incompatible with 1.17.1, i have compiled it myself with updated dependencies. this should work but it is provided with no support.

**Comment by motz0815** [comment]
Firstly, I will definitely not download a zip-file I got from a random person.

Thanks for your attempted contribution, but that is not how contributing works. If changes in code would have to be done, or updating dependencies, you could do that by opening a Pull Request with your changes. I will update the build-configuration myself ^^
