### ISSUE TITLE
Randomizer doesn't work on >=1.17

### ISSUE THREAD

**Issue by Ninja1143** [motz0815/Randomizer#2]

**Comment by motz0815** [comment]
Please point out your issue in more detail.
Are there any errors in the console?
Have you tried running the plugin on its own, without any others?
What is the output of /pl?
What version are you running?

**Comment by Ninja1143** [comment]
Oh mb so i tried saying /random shuffle but it didn't work so i said -pl and it showed that the randomizer was indeed there so i checked the log and it said it wasn't up to date even tho i downloaded the newest version of the randomizer and the server so i changed the server version to 1.17 instead of 1.17.1 to see if it would work but it didn't so i gave up

**Comment by motz0815** [comment]
I don't know if that's just written wrong, but the command is /randomizer shuffle, not /random shuffle.
Also, could you post the .log?

**Comment by Ninja1143** [comment]
its written wrong lol i'll post the log

**Comment by Ninja1143** [comment]
![Screenshot (212)](https://user-images.githubusercontent.com/88360682/128005483-e08d01f1-151f-434a-8af6-96dfc8a75acb.png)

**Comment by motz0815** [comment]
I have just updated Randomizer to fully support 1.17.
Check out Update 3.0.0: https://github.com/motz0815/Randomizer/releases/tag/3.0.0
