### ISSUE TITLE
'An internal error occurred while attempting to perform this command'

### ISSUE THREAD

**Issue by abskepeg** [motz0815/Randomizer#6]
Tryna run a 1.18.2 modded server on Aternos using the softwear Mohist (both plugins and mods) and i've installed the plugin onto aternos, added myself as an op and ive also done the java 11 download. But when i type in the /randomizer shuffle it gives me that error, 'An internal error occurred while attempting to perform this command'. 

It says that randomizer is active but doesn't work without the shuffle command

**Comment by motz0815** [comment]
Do you have access to the console? If so, please attach the latest.log or a screenshot of the entire error to this conversation.

**Comment by motz0815** [comment]
Is this issue still active, or have you managed to fix it? I can't reproduce your error.
